---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpuexecutioncap: 50
#   natdnshostresolver1: "on"
# network:
# - ["forwarded_port", {guest: 8080, host: 8080}]
# - ["forwarded_port", {guest: 8443, host: 8443, auto_correct: true}]

driver_config:
    use_vagrant_berkshelf_plugin: true
    require_chef_omnibus: 10.32.2

provisioner:
  name: chef_solo

platforms:
- name: ubuntu-14.04
  driver_config:
    box: opscode-ubuntu-14.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box

suites:
  - name: primary
    run_list:
      - recipe["default"]
    attributes:
